# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/5713534771DF0EFB/Development/Python/gerador_relatorios_graduacao/views/layouts/base.ui'
#
# Created: Fri May 13 06:58:48 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 420)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabPassos = QtGui.QTabWidget(self.centralwidget)
        self.tabPassos.setGeometry(QtCore.QRect(10, 0, 781, 371))
        self.tabPassos.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.tabPassos.setObjectName(_fromUtf8("tabPassos"))
        self.Perfil = QtGui.QWidget()
        self.Perfil.setObjectName(_fromUtf8("Perfil"))
        self.gridLayoutWidget = QtGui.QWidget(self.Perfil)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 286))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.grid_perfil = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grid_perfil.setMargin(0)
        self.grid_perfil.setObjectName(_fromUtf8("grid_perfil"))
        self.label_seletor = QtGui.QLabel(self.gridLayoutWidget)
        self.label_seletor.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.label_seletor.setObjectName(_fromUtf8("label_seletor"))
        self.grid_perfil.addWidget(self.label_seletor, 0, 0, 1, 1)
        self.btn_clr_perfil = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_clr_perfil.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_clr_perfil.setObjectName(_fromUtf8("btn_clr_perfil"))
        self.grid_perfil.addWidget(self.btn_clr_perfil, 2, 2, 1, 1)
        self.seletor_perfil = QtGui.QComboBox(self.gridLayoutWidget)
        self.seletor_perfil.setObjectName(_fromUtf8("seletor_perfil"))
        self.grid_perfil.addWidget(self.seletor_perfil, 0, 1, 1, 2)
        self.btn_cad_perfil = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_cad_perfil.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_cad_perfil.setObjectName(_fromUtf8("btn_cad_perfil"))
        self.grid_perfil.addWidget(self.btn_cad_perfil, 2, 1, 1, 1)
        self.form_perfil = QtGui.QFormLayout()
        self.form_perfil.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.form_perfil.setObjectName(_fromUtf8("form_perfil"))
        self.form_autor = QtGui.QLineEdit(self.gridLayoutWidget)
        self.form_autor.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.form_autor.setObjectName(_fromUtf8("form_autor"))
        self.form_perfil.setWidget(0, QtGui.QFormLayout.FieldRole, self.form_autor)
        self.matricula = QtGui.QLabel(self.gridLayoutWidget)
        self.matricula.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.matricula.setObjectName(_fromUtf8("matricula"))
        self.form_perfil.setWidget(1, QtGui.QFormLayout.LabelRole, self.matricula)
        self.form_matricula = QtGui.QLineEdit(self.gridLayoutWidget)
        self.form_matricula.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.form_matricula.setObjectName(_fromUtf8("form_matricula"))
        self.form_perfil.setWidget(1, QtGui.QFormLayout.FieldRole, self.form_matricula)
        self.universidade = QtGui.QLabel(self.gridLayoutWidget)
        self.universidade.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.universidade.setObjectName(_fromUtf8("universidade"))
        self.form_perfil.setWidget(3, QtGui.QFormLayout.LabelRole, self.universidade)
        self.form_universidade = QtGui.QLineEdit(self.gridLayoutWidget)
        self.form_universidade.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.form_universidade.setObjectName(_fromUtf8("form_universidade"))
        self.form_perfil.setWidget(3, QtGui.QFormLayout.FieldRole, self.form_universidade)
        self.departamento = QtGui.QLabel(self.gridLayoutWidget)
        self.departamento.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.departamento.setObjectName(_fromUtf8("departamento"))
        self.form_perfil.setWidget(4, QtGui.QFormLayout.LabelRole, self.departamento)
        self.form_departamento = QtGui.QLineEdit(self.gridLayoutWidget)
        self.form_departamento.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.form_departamento.setObjectName(_fromUtf8("form_departamento"))
        self.form_perfil.setWidget(4, QtGui.QFormLayout.FieldRole, self.form_departamento)
        self.local = QtGui.QLabel(self.gridLayoutWidget)
        self.local.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.local.setObjectName(_fromUtf8("local"))
        self.form_perfil.setWidget(5, QtGui.QFormLayout.LabelRole, self.local)
        self.form_local = QtGui.QLineEdit(self.gridLayoutWidget)
        self.form_local.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.form_local.setObjectName(_fromUtf8("form_local"))
        self.form_perfil.setWidget(5, QtGui.QFormLayout.FieldRole, self.form_local)
        self.autor = QtGui.QLabel(self.gridLayoutWidget)
        self.autor.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.autor.setObjectName(_fromUtf8("autor"))
        self.form_perfil.setWidget(0, QtGui.QFormLayout.LabelRole, self.autor)
        self.grid_perfil.addLayout(self.form_perfil, 1, 0, 1, 3)
        self.btn_prox_perfil = QtGui.QPushButton(self.Perfil)
        self.btn_prox_perfil.setGeometry(QtCore.QRect(650, 300, 121, 31))
        self.btn_prox_perfil.setStyleSheet(_fromUtf8("background-color:rgb(115, 189, 117);\n"
"border-radius:5px;\n"
"color:white;"))
        self.btn_prox_perfil.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_prox_perfil.setObjectName(_fromUtf8("btn_prox_perfil"))
        self.tabPassos.addTab(self.Perfil, _fromUtf8(""))
        self.Atributos = QtGui.QWidget()
        self.Atributos.setObjectName(_fromUtf8("Atributos"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.Atributos)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 761, 281))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.form_atributos = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.form_atributos.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.form_atributos.setMargin(0)
        self.form_atributos.setObjectName(_fromUtf8("form_atributos"))
        self.titulo = QtGui.QLabel(self.formLayoutWidget_2)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.form_atributos.setWidget(0, QtGui.QFormLayout.LabelRole, self.titulo)
        self.form_titulo = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.form_titulo.setObjectName(_fromUtf8("form_titulo"))
        self.form_atributos.setWidget(0, QtGui.QFormLayout.FieldRole, self.form_titulo)
        self.data = QtGui.QLabel(self.formLayoutWidget_2)
        self.data.setObjectName(_fromUtf8("data"))
        self.form_atributos.setWidget(1, QtGui.QFormLayout.LabelRole, self.data)
        self.form_data = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.form_data.setObjectName(_fromUtf8("form_data"))
        self.form_atributos.setWidget(1, QtGui.QFormLayout.FieldRole, self.form_data)
        self.disciplina = QtGui.QLabel(self.formLayoutWidget_2)
        self.disciplina.setObjectName(_fromUtf8("disciplina"))
        self.form_atributos.setWidget(2, QtGui.QFormLayout.LabelRole, self.disciplina)
        self.form_disciplina = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.form_disciplina.setObjectName(_fromUtf8("form_disciplina"))
        self.form_atributos.setWidget(2, QtGui.QFormLayout.FieldRole, self.form_disciplina)
        self.turma = QtGui.QLabel(self.formLayoutWidget_2)
        self.turma.setObjectName(_fromUtf8("turma"))
        self.form_atributos.setWidget(3, QtGui.QFormLayout.LabelRole, self.turma)
        self.form_turma = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.form_turma.setObjectName(_fromUtf8("form_turma"))
        self.form_atributos.setWidget(3, QtGui.QFormLayout.FieldRole, self.form_turma)
        self.professor = QtGui.QLabel(self.formLayoutWidget_2)
        self.professor.setObjectName(_fromUtf8("professor"))
        self.form_atributos.setWidget(4, QtGui.QFormLayout.LabelRole, self.professor)
        self.form_professor = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.form_professor.setObjectName(_fromUtf8("form_professor"))
        self.form_atributos.setWidget(4, QtGui.QFormLayout.FieldRole, self.form_professor)
        self.preambulo = QtGui.QLabel(self.formLayoutWidget_2)
        self.preambulo.setObjectName(_fromUtf8("preambulo"))
        self.form_atributos.setWidget(5, QtGui.QFormLayout.LabelRole, self.preambulo)
        self.form_preambulo = QtGui.QPlainTextEdit(self.formLayoutWidget_2)
        self.form_preambulo.setObjectName(_fromUtf8("form_preambulo"))
        self.form_atributos.setWidget(5, QtGui.QFormLayout.FieldRole, self.form_preambulo)
        self.btn_prox_atributos = QtGui.QPushButton(self.Atributos)
        self.btn_prox_atributos.setGeometry(QtCore.QRect(650, 300, 121, 31))
        self.btn_prox_atributos.setStyleSheet(_fromUtf8("background-color:rgb(115, 189, 117);\n"
"border-radius:5px;\n"
"color:white;"))
        self.btn_prox_atributos.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_prox_atributos.setObjectName(_fromUtf8("btn_prox_atributos"))
        self.tabPassos.addTab(self.Atributos, _fromUtf8(""))
        self.Dados = QtGui.QWidget()
        self.Dados.setObjectName(_fromUtf8("Dados"))
        self.verticalLayoutWidget = QtGui.QWidget(self.Dados)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 281))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vertical_layout_dados = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout_dados.setMargin(0)
        self.vertical_layout_dados.setObjectName(_fromUtf8("vertical_layout_dados"))
        self.label_desc_dados = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_desc_dados.setObjectName(_fromUtf8("label_desc_dados"))
        self.vertical_layout_dados.addWidget(self.label_desc_dados)
        self.tabela_dados = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.tabela_dados.setRowCount(6)
        self.tabela_dados.setColumnCount(2)
        self.tabela_dados.setObjectName(_fromUtf8("tabela_dados"))
        item = QtGui.QTableWidgetItem()
        self.tabela_dados.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabela_dados.setHorizontalHeaderItem(1, item)
        self.vertical_layout_dados.addWidget(self.tabela_dados)
        self.btn_prox_dados = QtGui.QPushButton(self.Dados)
        self.btn_prox_dados.setGeometry(QtCore.QRect(650, 300, 121, 31))
        self.btn_prox_dados.setStyleSheet(_fromUtf8("background-color:rgb(115, 189, 117);\n"
"border-radius:5px;\n"
"color:white;"))
        self.btn_prox_dados.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_prox_dados.setObjectName(_fromUtf8("btn_prox_dados"))
        self.tabPassos.addTab(self.Dados, _fromUtf8(""))
        self.Conteudo = QtGui.QWidget()
        self.Conteudo.setObjectName(_fromUtf8("Conteudo"))
        self.btn_prox_conteudo = QtGui.QPushButton(self.Conteudo)
        self.btn_prox_conteudo.setGeometry(QtCore.QRect(650, 300, 121, 31))
        self.btn_prox_conteudo.setStyleSheet(_fromUtf8("background-color:rgb(115, 189, 117);\n"
"border-radius:5px;\n"
"color:white;"))
        self.btn_prox_conteudo.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btn_prox_conteudo.setObjectName(_fromUtf8("btn_prox_conteudo"))
        self.tabPassos.addTab(self.Conteudo, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menubar)
        self.novo = QtGui.QAction(MainWindow)
        self.novo.setObjectName(_fromUtf8("novo"))
        self.salvar = QtGui.QAction(MainWindow)
        self.salvar.setObjectName(_fromUtf8("salvar"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.sair = QtGui.QAction(MainWindow)
        self.sair.setObjectName(_fromUtf8("sair"))
        self.config = QtGui.QAction(MainWindow)
        self.config.setObjectName(_fromUtf8("config"))
        self.sobre = QtGui.QAction(MainWindow)
        self.sobre.setObjectName(_fromUtf8("sobre"))
        self.actionAdicionar = QtGui.QAction(MainWindow)
        self.actionAdicionar.setObjectName(_fromUtf8("actionAdicionar"))
        self.actionEditar = QtGui.QAction(MainWindow)
        self.actionEditar.setObjectName(_fromUtf8("actionEditar"))
        self.menuArquivo.addAction(self.novo)
        self.menuArquivo.addAction(self.salvar)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.sair)
        self.menuAjuda.addAction(self.config)
        self.menuAjuda.addAction(self.sobre)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.label_seletor.setBuddy(self.label_seletor)

        self.retranslateUi(MainWindow)
        self.tabPassos.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabPassos, self.seletor_perfil)
        MainWindow.setTabOrder(self.seletor_perfil, self.form_autor)
        MainWindow.setTabOrder(self.form_autor, self.form_matricula)
        MainWindow.setTabOrder(self.form_matricula, self.form_universidade)
        MainWindow.setTabOrder(self.form_universidade, self.form_departamento)
        MainWindow.setTabOrder(self.form_departamento, self.form_local)
        MainWindow.setTabOrder(self.form_local, self.btn_cad_perfil)
        MainWindow.setTabOrder(self.btn_cad_perfil, self.btn_clr_perfil)
        MainWindow.setTabOrder(self.btn_clr_perfil, self.btn_prox_perfil)
        MainWindow.setTabOrder(self.btn_prox_perfil, self.form_titulo)
        MainWindow.setTabOrder(self.form_titulo, self.form_data)
        MainWindow.setTabOrder(self.form_data, self.form_disciplina)
        MainWindow.setTabOrder(self.form_disciplina, self.form_turma)
        MainWindow.setTabOrder(self.form_turma, self.form_professor)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RelataLab", None))
        self.label_seletor.setText(_translate("MainWindow", "Selecione o perfil de usuário ou cadastre um novo:", None))
        self.btn_clr_perfil.setText(_translate("MainWindow", "Limpar", None))
        self.btn_cad_perfil.setText(_translate("MainWindow", "Cadastrar", None))
        self.form_autor.setPlaceholderText(_translate("MainWindow", "Ex: Joana da Silva", None))
        self.matricula.setText(_translate("MainWindow", "Número de Matrícula", None))
        self.form_matricula.setPlaceholderText(_translate("MainWindow", "Ex: 11511EAA001", None))
        self.universidade.setText(_translate("MainWindow", "Universidade", None))
        self.form_universidade.setPlaceholderText(_translate("MainWindow", "Ex: Universidade Federal de Uberlândia", None))
        self.departamento.setText(_translate("MainWindow", "Departamento", None))
        self.form_departamento.setPlaceholderText(_translate("MainWindow", "Ex: Faculdade de Engenharia Elétrica", None))
        self.local.setText(_translate("MainWindow", "Local", None))
        self.form_local.setPlaceholderText(_translate("MainWindow", "Ex: Uberlândia, Minas Gerais", None))
        self.autor.setText(_translate("MainWindow", "Autor", None))
        self.btn_prox_perfil.setText(_translate("MainWindow", "Próximo", None))
        self.tabPassos.setTabText(self.tabPassos.indexOf(self.Perfil), _translate("MainWindow", "Perfil", None))
        self.titulo.setText(_translate("MainWindow", "Título", None))
        self.form_titulo.setPlaceholderText(_translate("MainWindow", "Ex: Lei de Ohm e Resistores", None))
        self.data.setText(_translate("MainWindow", "Data", None))
        self.form_data.setPlaceholderText(_translate("MainWindow", "Ex: 19 de Março de 2016", None))
        self.disciplina.setText(_translate("MainWindow", "Disciplina", None))
        self.form_disciplina.setPlaceholderText(_translate("MainWindow", "Ex: Física II", None))
        self.turma.setText(_translate("MainWindow", "Turma", None))
        self.form_turma.setPlaceholderText(_translate("MainWindow", "Ex: Turma I", None))
        self.professor.setText(_translate("MainWindow", "Professor", None))
        self.form_professor.setPlaceholderText(_translate("MainWindow", "Ex: João da Silva", None))
        self.preambulo.setText(_translate("MainWindow", "Preâmbulo", None))
        self.btn_prox_atributos.setText(_translate("MainWindow", "Próximo", None))
        self.tabPassos.setTabText(self.tabPassos.indexOf(self.Atributos), _translate("MainWindow", "Atributos", None))
        self.label_desc_dados.setText(_translate("MainWindow", "Informe os dados abaixo:", None))
        item = self.tabela_dados.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X", None))
        item = self.tabela_dados.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y", None))
        self.btn_prox_dados.setText(_translate("MainWindow", "Próximo", None))
        self.tabPassos.setTabText(self.tabPassos.indexOf(self.Dados), _translate("MainWindow", "Dados", None))
        self.btn_prox_conteudo.setText(_translate("MainWindow", "Próximo", None))
        self.tabPassos.setTabText(self.tabPassos.indexOf(self.Conteudo), _translate("MainWindow", "Conteúdo", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.novo.setText(_translate("MainWindow", "Novo", None))
        self.salvar.setText(_translate("MainWindow", "Salvar", None))
        self.actionSair.setText(_translate("MainWindow", "Sair", None))
        self.sair.setText(_translate("MainWindow", "Sair", None))
        self.config.setText(_translate("MainWindow", "Configurações", None))
        self.sobre.setText(_translate("MainWindow", "Sobre o RelataLab", None))
        self.actionAdicionar.setText(_translate("MainWindow", "Adicionar", None))
        self.actionEditar.setText(_translate("MainWindow", "Editar", None))

